version: '3.9'

services:
  django:
    restart: always
    build: . # path to Dockerfile
    command: sh -c "gunicorn --bind 0.0.0.0:8000 settings.wsgi:application --reload"
    volumes:
      - .:/project
      - static:/project/static
    expose:
      - 8000
    env_file:
     - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}
      - DEBUG=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - 0.0.0.0:${WEB_PORT}:8000

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data_dev:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 0.0.0.0:${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}


volumes:
    pg_data_dev:
    static:
